spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/testGina
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      default_batch_fetch_size: 1000
    properties:
      hibernate:
      show_sql: true
      format_sql: true
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 2000

logging.level:
  org.hibernate.SQL: debug

swagger-ui:
  path: /
  disable-swagger-default-url: true
  display-request-duration: true
  operations-sorter: alpha
  doc-expansion: none
